apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bookinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/bhargavimandala/fluxcdv2-demo/flux-v2/bookinfo
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bookinfo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-v2/bookinfo-release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  