apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-release-bookinfo
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: bookinfo
      version: '0.1.0'
      sourceRef:
        kind: GitRepository
        name: bookinfo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2