apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-podinfo
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      version: '4.0.1'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
