apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-nginx-chart
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: helm-nginx-chart
      version: '0.1.0'
      sourceRef:
        kind: GitRepository
        name: helm-nginx-chart
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
